import React from "react";
import Questions from "@/app/components/theme-pages/faq/Questions";
import StillHaveQst from "@/app/components/theme-pages/faq/StillHaveQst";
import type { Metadata } from "next";
import ThemeBreadcrumb from "../../layout/shared/breadcrumb/ThemeBreadcrumb";
export const metadata: Metadata = {
  title: "FAQ Page",
  description: "Generated by create next app",
};


const faq = () => {
  return (
    <>
      <ThemeBreadcrumb title="FAQ" />
      <Questions />
      <StillHaveQst />
    </>
  );
};

export default faq;
