import React from "react";
import ApexGradientChart from "@/app/components/charts/ApexGradientChart";
import type { Metadata } from "next";
import ThemeBreadcrumb from "../../layout/shared/breadcrumb/ThemeBreadcrumb";
export const metadata: Metadata = {
  title: "Gradient Chart",
  description: "Generated by create next app",
};
const GradientChart = () => {
  return (
    <>
      <ThemeBreadcrumb title="Chart Apex Gradient" />
      <ApexGradientChart />
    </>
  );
};

export default GradientChart;
