
import React from "react";
import CheckBoxTable from '@/app/components/tables/checkbox/index'
import type { Metadata } from "next";
import ThemeBreadcrumb from "../../layout/shared/breadcrumb/ThemeBreadcrumb";
export const metadata: Metadata = {
  title: "CheckBox Table",
  description: "Generated by create next app",
};


const CheckboxTable = () => {

  return (
    <>
      <ThemeBreadcrumb title="Checkbox Table" />
      <CheckBoxTable/>
    </>
  );
};

export default CheckboxTable;
