import RollBaseIndex from "@/app/components/theme-pages/casl";
import type { Metadata } from "next";
import ThemeBreadcrumb from "../../layout/shared/breadcrumb/ThemeBreadcrumb";
export const metadata: Metadata = {
  title: "CASL Page",
  description: "Generated by create next app",
};



const RollBase = () => {

  return (
    <>
      <ThemeBreadcrumb title="Rollbase Access" />
      <RollBaseIndex/>
    </>
  );
};

export default RollBase;
