import React from "react";
import ApexCandleStick from "@/app/components/charts/ApexCandleSticks";
import type { Metadata } from "next";
import ThemeBreadcrumb from "../../layout/shared/breadcrumb/ThemeBreadcrumb";
export const metadata: Metadata = {
  title: "Candlestick Chart",
  description: "Generated by create next app",
};
const CandleStick = () => {
  return (
    <>
      <ThemeBreadcrumb title="Chart Apex Candlestick" />
      <ApexCandleStick />
    </>
  );
};

export default CandleStick;
