
import React from "react";
import ApexColumnChart from "@/app/components/charts/ApexColumnChart";
import type { Metadata } from "next";
import ThemeBreadcrumb from "../../layout/shared/breadcrumb/ThemeBreadcrumb";
export const metadata: Metadata = {
  title: "Column Chart",
  description: "Generated by create next app",
};

const ColumnChart = () => {

  return (
    <>
      <ThemeBreadcrumb title="Chart Apex Column" />
      <ApexColumnChart/>
    </>
  );
};

export default ColumnChart;
