import React from "react";
import ApexLineChart from "@/app/components/charts/ApexLineChart";
import type { Metadata } from "next";
import ThemeBreadcrumb from "../../layout/shared/breadcrumb/ThemeBreadcrumb";
export const metadata: Metadata = {
  title: "Line Chart",
  description: "Generated by create next app",
};

const LineChart = () => {
  return (
    <>
      <ThemeBreadcrumb title="Chart Apex Line" />
      <ApexLineChart />
    </>
  );
};

export default LineChart;
