

import Logo from "@/app/DashboardLayout/layout/shared/logo/Logo";
import CardBox from "@/app/components/shared/CardBox";
import React from "react";
import SocialButtons from "../../authforms/SocialButtons";
import AuthLogin from "../../authforms/AuthLogin";
import Link from "next/link";
import type { Metadata } from "next";
import rightBgimg from "/public/images/backgrounds/leaf-right.png"
import leftBgimg from "/public/images/backgrounds/leaf-left.png"
import Image from "next/image";
import FullLogo from "@/app/DashboardLayout/layout/shared/logo/FullLogo";
import AuthForgotPassword from "../../authforms/AuthForgotPassword";
export const metadata: Metadata = {
  title: "Boxed Forgot Authentication",
  description: "Generated by create next app",
};
const BoxedForgotpwd = () => {
  return (
    <>
      <div className="relative overflow-hidden h-screen bg-lightsubtle dark:bg-dark">
      <div className="absolute start-0 bottom-0 z-1 md:block hidden">
            <Image src={leftBgimg} alt="img"/>
      </div>
        <div className="flex h-full justify-center items-center px-4">
          <CardBox className="md:w-[450px] w-full border-none">
          <div className="w-full">
                <div className="flex justify-center mb-4">
                <FullLogo/>
                </div>
                 <p className="text-bodyclr dark:text-darkmuted text-center text-sm font-medium">
                 Please enter the email address associated with your account and We will email you a link to reset your password.
                 </p>
                 <AuthForgotPassword />
                 <Link href='/auth/auth2/login' className="rounded-full bg-lightprimary text-center font-medium block text-primary mt-3 py-2 px-4 hover:bg-primary hover:text-white w-full">
          Back to login
        </Link>
               </div>
          </CardBox>
        </div>
        <div className="absolute end-0 bottom-0 z-1 md:block hidden">
            <Image src={rightBgimg} alt="img"/>
      </div>
      </div>
    </>
  );
};

export default BoxedForgotpwd;


