import PricingIndex from "@/app/components/theme-pages/pricing";
import type { Metadata } from "next";
import ThemeBreadcrumb from "../../layout/shared/breadcrumb/ThemeBreadcrumb";
export const metadata: Metadata = {
  title: "Pricing Page",
  description: "Generated by create next app",
};

const Pricing = () => {
  return (
    <>
      <ThemeBreadcrumb title="Pricing"/>
      <PricingIndex />
    </>
  );
};

export default Pricing;
