

import CardBox from "@/app/components/shared/CardBox";
import React from "react";
import type { Metadata } from "next";
import rightBgimg from "/public/images/backgrounds/leaf-right.png"
import leftBgimg from "/public/images/backgrounds/leaf-left.png"
import Image from "next/image";
import AuthTwoSteps from "../../authforms/AuthTwoSteps";
import FullLogo from "@/app/DashboardLayout/layout/shared/logo/FullLogo";
export const metadata: Metadata = {
  title: "BoxedTwoStep Authentication",
  description: "Generated by create next app",
};
const BoxedTwoStep = () => {
  return (
    <>
      <div className="relative overflow-hidden h-screen bg-lightsubtle dark:bg-dark">
      <div className="absolute start-0 bottom-0 z-1 md:block hidden">
            <Image src={leftBgimg} alt="img"/>
      </div>
        <div className="flex h-full justify-center items-center px-4">
                   <CardBox className="md:w-[450px] w-full border-none">
             <div className="mx-auto py-0 mb-4">
               <FullLogo />
             </div>
             <p className="text-bodyclr dark:text-darkmuted text-sm font-medium text-center">
             We sent a verification code to your mobile. Enter the code from the mobile in the field below.
             </p>
             <h6 className="text-sm font-bold my-4 text-center">******1234</h6>
             <AuthTwoSteps />
           </CardBox>
        </div>
        <div className="absolute end-0 bottom-0 z-1 md:block hidden">
            <Image src={rightBgimg} alt="img"/>
      </div>
      </div>
    </>
  );
};

export default BoxedTwoStep;

